<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net472</TargetFrameworks>
    <RootNamespace>PiDbg</RootNamespace>
    <AssemblyName>PiDbg.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meadow.Daemon.Contracts\Meadow.Daemon.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Grpc.Core" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
